export default {
    CUSTOM_ERROR:{
        UNAUTHORIZED:'UNAUTHORIZED',
        REFRESH_TOKEN_EXPIRED:'REFRESH_TOKEN_EXPIRED',
        ACCESS_TOKEN_EXPIRED:'ACCESS_TOKEN_EXPIRED',
        TOKEN_EXPIRED:'TOKEN_EXPIRED',
        AUTHENTICATION_REQUIRED:'AUTHENTICATION_REQUIRED',
        REFRESH_TOKEN_REQUIRED:'REFRESH_TOKEN_REQUIRED',
        USER_UNCONFIRMED:'USER_UNCONFIRMED'
    }
}